export const INSIGHTS = {
  SHORTEST_GAME_BY_MOVES: "SHORTEST_GAME_BY_MOVES",
  LONGEST_GAME_BY_MOVES: "LONGEST_GAME_BY_MOVES",
  AVERAGE_MOVE_COUNT: "AVERAGE_MOVE_COUNT",
  LONGEST_MOVE_BY_TIME: "LONGEST_MOVE_BY_TIME",
  PLAYER_WITH_HIGHEST_MOVE_AVERAGE: "PLAYER_WITH_HIGHEST_MOVE_AVERAGE",
  PLAYER_WITH_LOWEST_MOVE_AVERAGE: "PLAYER_WITH_LOWEST_MOVE_AVERAGE",
  MOST_ACCURATE_GAME: "MOST_ACCURATE_GAME",
  MOST_DYNAMIC_GAME: "MOST_DYNAMIC_GAME",
  MOST_USED_OPENING: "MOST_USED_OPENING",
  MOST_USED_OPENING_MOVE_WHITE: "MOST_USED_OPENING_MOVE_WHITE",
  MOST_USED_OPENING_MOVE_BLACK: "MOST_USED_OPENING_MOVE_BLACK",
  MOST_ACCURATE_PLAYER: "MOST_ACCURATE_PLAYER",
  HIGHEST_WINNING_STREAK: "HIGHEST_WINNING_STREAK",
  HIGHEST_LOSING_STREAK: "HIGHEST_LOSING_STREAK",
  PLAYER_WITH_MOST_CHECKMATES_WIN: "PLAYER_CHECKMATES_WIN",
  PLAYER_WITH_MOST_CHECKMATES_LOSS: "PLAYER_CHECKMATES_LOSS",
  PLAYER_WITH_MOST_TIMEOUT_WIN: "PLAYER_CHECKMATES_WIN",
  PLAYER_WITH_MOST_TIMEOUT_LOSS: "PLAYER_CHECKMATES_LOSS",
};

export const INSIGHT_SENTENCE = {
  SHORTEST_GAME_BY_MOVES: "whitePLayer vs blackPlayer had the longest game with insightValue moves with {Winner} Winning",
  LONGEST_GAME_BY_MOVES: "whitePLayer vs blackPlayer had the shortest game with only insightValue moves with {Winner} winning ",
  AVERAGE_MOVE_COUNT: "insightValue",
  LONGEST_MOVE_BY_TIME: "Move ${item.moveNo || 'N/A'} by ${item.side || 'N/A'} took ${item.timeTaken?.toFixed(2) || 'N/A'} seconds.",
  PLAYER_WITH_HIGHEST_MOVE_AVERAGE: "player played the longest games with the average of insightValue moves",
  PLAYER_WITH_LOWEST_MOVE_AVERAGE: "player played the shortest games with the average of insightValue moves",
  MOST_ACCURATE_GAME: "${item.players?.white?.name || 'Unknown'} vs ${item.players?.black?.name || 'Unknown'} had an average accuracy of ${item.value?.toFixed(2)}%.",
  MOST_DYNAMIC_GAME: "${item.players?.white?.user?.name || 'Unknown'} vs ${item.players?.black?.user?.name || 'Unknown'} had ${item.value} turn arounds.",
  MOST_USED_OPENING: "${item.openingName || 'Unknown'} was used ${item.noOfTimes || 'N/A'} times.",
  MOST_USED_OPENING_MOVE_WHITE: "opening was used moveNumber times",
  MOST_USED_OPENING_MOVE_BLACK: "opening was used moveNumber times",
  MOST_ACCURATE_PLAYER: "${item.playerName || 'Unknown'} had an average accuracy of ${item.averageAccuracy?.toFixed(2) || 'N/A'}% over ${item.noOfMatches || 'N/A'} matches.",
  HIGHEST_WINNING_STREAK: "player won insightValue matches in a arow",
  HIGHEST_LOSING_STREAK: "player lost insightValue matches in a arow",
  PLAYER_WITH_MOST_CHECKMATES_WIN: "player won number matches with a checkmate",
  PLAYER_WITH_MOST_CHECKMATES_LOSS: "player lost number matches with a checkmate",
  PLAYER_WITH_MOST_TIMEOUT_WIN: "player won number matches with a timeout",
  PLAYER_WITH_MOST_TIMEOUT_LOSS: "player lost number matches with a checkmate",
};