export const INSIGHTS = {
  SHORTEST_GAME_BY_MOVES: "SHORTEST_GAME_BY_MOVES",
  LONGEST_GAME_BY_MOVES: "LONGEST_GAME_BY_MOVES",
  LONGEST_MOVE_BY_TIME: "LONGEST_MOVE_BY_TIME",
  MOST_ACCURATE_GAME: "MOST_ACCURATE_GAME",
  MOST_DYNAMIC_GAME: "MOST_DYNAMIC_GAME",
  MOST_USED_OPENING: "MOST_USED_OPENING",
  MOST_ACCURATE_PLAYER: "MOST_ACCURATE_PLAYER",
  HIGHEST_WINNING_STREAK: "HIGHEST_WINNING_STREAK",
};